require 'yaml'
base_dir = File.expand_path(File.dirname(__FILE__))
cluster = YAML.load_file(File.join(base_dir, "cluster.yml"))

def define_vm config, box, name, i
    config.vm.define name do |cfg|
      cfg.vm.box = box
      cfg.vm.network "public_network", bridge: "wlp3s0" #, ip: "192.168.56.10#{i}"
      cfg.vm.provision "shell", inline: "ip route del default via 10.0.2.2 dev eth0  proto static  metric 100", privileged: true
    end
end

Vagrant.configure("2") do |config|
  vms = ["master", "etcd"]
  for i in 1..cluster["nodes"] do
    vms << "node#{i}"
  end

  vms.each_with_index do |name, index|
    define_vm config, cluster["box"], name, index
  end
end
